Repository IsyFact/isyfact-standards, pull requests merged in 2023-10, with the labels that each got.

#66 ISY-54: migration guide for switching to isy-security
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
Labels: high

#93 ISY-219: migration guide isy-security - document annotation for user authentication
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
Labels: high

#67 ISY-183 Migrationsleitfaden ergaenzen Bridgemodule
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
Labels: medium

#92 Draft: Feature/ifs 2596 endredaktion und aenderungen dokumentation
  isyfact-standards-doc/src/docs/antora/modules/isy-security/images/konzept/ServiceGateway-Authentifizierung.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/thisdoc.adoc
Labels: high

#88 ISY-342: Release workflow
  .github/workflows/maven_build.yml
  .github/workflows/maven_build_template.yml
  .github/workflows/maven_deploy_template.yml
  .github/workflows/maven_release.yml
  pom.xml
Labels: ci, high

#89 ISY-342: Release workflow for release/2.x branch
  .github/workflows/maven_build.yml
  .github/workflows/maven_release.yml
Labels: ci, high

#100 Feature/ifs 2596 auth gateway spaeter
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
Labels: medium

#105 ISY-342: Fix QG in Release Workflow
  .github/workflows/maven_build_template.yml
  .github/workflows/maven_release.yml
Labels: high

#106 ISY-342: Fix QG in Release Workflow release/2.x
  .github/workflows/maven_release.yml
Labels: high

#103 ISY-386: DependaBot Auto-Merge Workflow
  .github/dependabot.yml
  .github/workflows/dependabot_merge.yml
Labels: medium

#113 Feature/isy 516 setup toast notification as sticky
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/bedienkonzept.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/changelog.adoc
Labels: ready for review

#104 DependaBot Auto-Merge Workflow for release/2.x
  .github/workflows/dependabot_merge.yml
Labels: medium

#122 Feature/isy 514 bedienkonzept replaced fontawesome icons with primeicons
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/arrow-circle-down.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/arrow-circle-left.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/arrow-circle-right.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/arrow-up-right.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/bell.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/bookmark-fill.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/calendar.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/car.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/check-circle.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/check-square.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/check.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/clock.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/cog.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/download.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/envelope.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/eraser.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/exclamation-triangle.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/eye.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/file.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/filter-fill.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/folder-open.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/history.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/id-card.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/image.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/info-circle.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/language.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/list.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/minus.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/paperclip.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/pencil.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/plus.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/print.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/refresh.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/reply.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/save.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/search.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/share-alt.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/sign-in.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/sign-out.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/star-fill.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/sync.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/times.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/trash.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/unlock.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/upload.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/images/primeicons/user.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/bedienkonzept.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/generierung/generierung-antora.adoc
Labels: blocked, refactor

#107 ISY-312: Scan OS Dependencies for Vulnerabilities
  .github/workflows/maven_dependency_scan.yml
  .github/workflows/maven_dependency_scan_template.yml
  .github/workflows/maven_release.yml
Labels: ci

#101 ISY-343: Job to trigger documentation build
  .github/workflows/docs_build.yml
Labels: ci, high

#155 [Sprint 89] ISY-382: Release Isyfact Standards 3.0.0
  CHANGELOG.md
  isy-batchrahmen/pom.xml
  isy-serviceapi-core/pom.xml
  isyfact-standards-doc/src/docs/antora/antora.yml
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/releasenotes.adoc
Labels: high
