Repository IsyFact/isyfact-standards, pull requests merged in 2023-09, with the labels that each got.

#73 ISY-279: Use SonarScan Job on Release/2.x Branch
  .github/workflows/maven.yml
Labels: ci, ready for review, high

#56 ISY-151: Maven workflow for release/2.x branch
  .github/workflows/maven.yml
Labels: ci, ready for review, high

#51 isyfact-products-bom: Explizite H2 Version entfernt
  isyfact-products-bom/CHANGELOG.md
  isyfact-products-bom/pom.xml
Labels: dependencies, approved, low

#68 ISY-139: Spring Boot 2.7.15
  CHANGELOG.md
  isyfact-products-bom/CHANGELOG.md
  isyfact-products-bom/pom.xml
  pom.xml
Labels: dependencies, approved, high

#64 ISY-147: isy-security revision
  isy-security/CHANGELOG.md
  isy-security/src/main/java/de/bund/bva/isyfact/security/autoconfigure/IsyOAuth2ClientAutoConfiguration.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/config/IsyOAuth2ClientConfigurationProperties.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/Authentifizierungsmanager.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ClientCredentialsAuthenticationToken.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ClientCredentialsAuthorizedClientAuthenticationProvider.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ClientCredentialsClientRegistrationAuthenticationProvider.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ManualClientCredentialsAuthenticationToken.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProvider.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationToken.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordClientRegistrationAuthenticationProvider.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/token/AbstractClientRegistrationAuthenticationToken.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/token/AbstractIsyAuthenticationToken.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/token/ClientCredentialsClientRegistrationAuthenticationToken.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/token/ClientCredentialsRegistrationIdAuthenticationToken.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/token/PasswordClientRegistrationAuthenticationToken.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/util/BhknzHeaderConverterBuilder.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/AbstractOidcProviderTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/autoconfigure/IsySecurityAutoConfigurationTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/AuthentifizierungsmanagerTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/AuthentifizierungsmanagerWithoutClientsConfiguredTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ClientCredentialsAuthorizedClientAuthenticationProviderTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ClientCredentialsClientRegistrationAuthenticationProviderTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordClientRegistrationAuthenticationProviderTest.java
  isy-security/src/test/resources/application-test-clients.yaml
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
Labels: high

#44 IFS-1885 Umsetzung: Weitergabe des Tokens an Nachbarsysteme
  isy-security/CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
Labels: feat, ready for review, high

#61 Feature/ifs 2483 ueberarbeitung sst authentifizierungsmanager
  isyfact-standards-doc/src/docs/antora/modules/isy-security/images/konzept/security-schnittstellen.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-security/images/konzept/software-architektur-berechtigungspruefung.png
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
Labels: high

#54 ISY-136: Fix findings from Code Climate
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
  isy-konfiguration/src/main/java/de/bund/bva/isyfact/konfiguration/common/impl/PropertyKonfiguration.java
  isy-konfiguration/src/main/java/de/bund/bva/isyfact/konfiguration/common/impl/ReloadablePropertyProvider.java
  isy-logging/src/main/java/de/bund/bva/isyfact/logging/util/BeanToMapConverter.java
  isy-persistence/src/main/java/de/bund/bva/isyfact/persistence/datasource/IsyDataSource.java
  isy-persistence/src/main/java/de/bund/bva/isyfact/persistence/usertype/EnumUserType.java
  isy-persistence/src/main/java/de/bund/bva/isyfact/persistence/usertype/EnumWithIdUserType.java
  isy-polling/src/main/java/de/bund/bva/isyfact/polling/annotation/PollingAktionInterceptor.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/serviceimpl/ReflectiveExceptionMappingSource.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/serviceimpl/ServiceFactoryBean.java
  isy-sicherheit/src/main/java/de/bund/bva/isyfact/sicherheit/impl/XmlAccess.java
  isy-sonderzeichen/src/main/java/de/bund/bva/isyfact/sonderzeichen/stringlatin1_1/core/transformation/impl/AbstractTransformator.java
  isy-ueberwachung/src/main/java/de/bund/bva/isyfact/ueberwachung/common/konstanten/EreignisSchluessel.java
Labels: fix, high

#74 [Sprint 78] IFS-2561 optionale rollenrechte
  CHANGELOG.md
  isy-security/CHANGELOG.md
  isy-security/src/main/java/de/bund/bva/isyfact/security/config/IsySecurityConfigurationProperties.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/xmlparser/RolePrivilegesMapper.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/authentication/RolePrivilegesMapperTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/autoconfigure/IsySecurityAutoConfigurationTest.java
  isy-security/src/test/resources/resources/sicherheit/rollenrechte-no-application-id.xml
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
Labels: feat, ready for review, medium

#42 IFS-2416 Umstellung task auf security
  CHANGELOG.md
  isy-task/CHANGELOG.md
  isy-task/pom.xml
  isy-task/src/main/java/de/bund/bva/isyfact/task/autoconfigure/IsyTaskAutoConfiguration.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/monitoring/IsyTaskAspect.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/security/Authenticator.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/security/AuthenticatorFactory.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactory.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/NoOpAuthenticator.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/NoOpAuthenticatorFactory.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/sicherheit/impl/IsySicherheitAuthenticator.java
  isy-task/src/main/java/de/bund/bva/isyfact/task/sicherheit/impl/IsySicherheitAuthenticatorFactory.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/AbstractOidcProviderTest.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskAuthentication.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskAuthenticationTasks.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskDeactivatedTasks.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskDeactivation.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskScheduledProgrammatically.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactoryTest.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/test/AccessManagerDummy.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/test/AuthentifizierungsErgebnisDummy.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/test/config/TestConfig.java
  isy-task/src/test/java/de/bund/bva/isyfact/task/test/monitoring/IsyTaskAspectTest.java
  isy-task/src/test/resources/application-security-test.properties
  isy-task/src/test/resources/application.properties
  isy-task/src/test/resources/resources/sicherheit/rollenrechte.xml
  isy-ueberwachung/src/test/resources/resources/sicherheit/rollenrechte.xml
  isyfact-standards-bom/pom.xml
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben/inhalt.adoc
Labels: feat, breaking change, high

#65 ISY-83: auth annotation
  isy-security/CHANGELOG.md
  isy-security/pom.xml
  isy-security/src/main/java/de/bund/bva/isyfact/security/autoconfigure/IsyOAuth2ClientAutoConfiguration.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/annotation/Authenticate.java
  isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/annotation/AuthenticateInterceptor.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/autoconfigure/IsySecurityAutoConfigurationTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/example/service/ExampleMethodAuthentication.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/annotation/CustomAuthenticateInterceptorTest.java
  isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/annotation/MethodAuthenticationTest.java
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
Labels: ready for review, high

#46 IFS-1853: Umstellung isy-batchrahmen auf isy-security
  CHANGELOG.md
  isy-batchrahmen/CHANGELOG.md
  isy-batchrahmen/pom.xml
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/KommandozeilenParser.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konstanten/BatchRahmenEreignisSchluessel.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konstanten/KonfigurationSchluessel.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/protokoll/BatchErgebnisProtokoll.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/rahmen/AuthenticationCredentials.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/rahmen/BatchAusfuehrungsBean.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/rahmen/BatchReturnCode.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/config/BatchSecurityConfiguration.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/launcher/BatchLauncher.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/protokoll/DefaultBatchErgebnisProtokoll.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/protokoll/XmlProtokollGenerator.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/rahmen/Batchrahmen.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/rahmen/impl/BatchrahmenImpl.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/rahmen/impl/StatusHandler.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/persistence/rahmen/BatchStatus.java
  isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/persistence/rahmen/BatchStatusDao.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/AnwendungTestConfig.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/BatchrahmenTest.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/BatchrahmenTestConfig.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/AufrufKontextTestBatch.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/BasicTestBatch.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/ErrorTestBatch.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/GesicherterTestBatch.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/GesicherterTestBatch2.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/InfiniteTestBatch.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/ReturnCodeTestBatch.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/config/AbstractOidcProviderTest.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/sicherheit/AccessManagerStub.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/sicherheit/AuthentifzierungErgebnisStub.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/test/BatchrahmenTest.java
  isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/test/TestBatchLauncherTest.java
  isy-batchrahmen/src/test/resources/application.properties
  isy-batchrahmen/src/test/resources/resources/batch/aufruf-kontext-test-batch-config.properties
  isy-batchrahmen/src/test/resources/resources/batch/gesicherter-test-batch-1-config.properties
  isy-batchrahmen/src/test/resources/resources/batch/gesicherter-test-batch-authenticated-client-credentials-config.properties
  isy-batchrahmen/src/test/resources/resources/batch/gesicherter-test-batch-authenticated-ropc-config.properties
  isy-batchrahmen/src/test/resources/resources/batch/gesicherter-test-batch-without-roles-config.properties
  isy-batchrahmen/src/test/resources/resources/batch/gesicherter-test-batch-wrong-user-config.properties
  isy-batchrahmen/src/test/resources/resources/batch/gesicherter-test-batch2-1-config.properties
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
Labels: feat, breaking change, high

#50 IFS-2502: Migrationsleitfaden ergaenzen HTTP-Invoker
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-serviceapi-core/images/nutzungsvorgaben/IF3_calls.dn.png
  isyfact-standards-doc/src/docs/antora/modules/isy-serviceapi-core/pages/nutzungsvorgaben/inhalt.adoc
Labels: docs, high

#49 Migrationsleitfaden isy-batchrahmen auf isy-security
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
Labels: docs, high

#45 IFS-2488: Paralleles Beibehalten von HTTP-Invoker
  CHANGELOG.md
  isy-serviceapi-core/CHANGELOG.md
  isy-serviceapi-core/pom.xml
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/autoconfigure/IsyServiceApiSecurityAutoConfiguration.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/AufrufKontextToRemoteInvocationFactory.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/CreateAufrufKontextToStrategy.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/DefaultCreateAufrufKontextToStrategy.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/IsyHttpInvokerClientInterceptor.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/IsyHttpInvokerServiceExporter.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/TimeoutWiederholungHttpInvokerRequestExecutor.java
  isy-serviceapi-core/src/main/resources/META-INF/spring.factories
  isy-serviceapi-core/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/autoconfigure/IsyServiceApiCoreAutoConfigurationSecurityTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/autoconfigure/IsyServiceApiCoreAutoConfigurationSicherheitTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/StelltLoggingKontextBereitAdvisorTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/StelltLoggingKontextBereitTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aufrufkontext/TestConfig.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/FillAufrufKontextToTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/IsyHttpInvokerServiceExporterIntegrationTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/TimeoutWiederholungHttpInvokerRequestExecutorIntegrationTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/service/httpinvoker/v1_0_0/DummyServiceImpl.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/service/httpinvoker/v1_0_0/DummyServiceRemoteBean.java
  isy-serviceapi-core/src/test/resources/resources/sicherheit/rollenrechte.xml
Labels: feat, ready for review, high

#47 IFS-1887: Anpassung der Nutzungsvorgaben isy-security
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/images/nutzungsvorgaben/authentifizierungsmanager.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-security/images/nutzungsvorgaben/berechtigungsmanager.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-security/images/nutzungsvorgaben/security.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben/inhalt.adoc
Labels: docs, high

#43 Migrationsleitfaden zur Umstellung von isy-task auf isy-security
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
Labels: docs, high
