Repository IsyFact/isyfact-standards, pull requests merged in 2024-08, with the labels that each got.

#505 feat: IFS-3611 Create pr_agent.yml
  .github/workflows/pr_agent.yml
Labels: configuration changes, Review effort [1-5]: 2

#511 docs: IFS-3750 remove building block configuration
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/bausteine/images/bausteine.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/bausteine/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/bausteine/pages/bausteine.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/detailkonzept-anwendungskern/SpringBeansBeispiel.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-anwendungskern/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/images/tutorial/Fachliche_Komponente.png
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/konzept/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/konzept/docinfo.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/konzept/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/konzept/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/konzept/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/nutzungsvorgaben/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/nutzungsvorgaben/docinfo.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/nutzungsvorgaben/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-konfiguration/pages/nutzungsvorgaben/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-logging/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-task/images/konzept/bausteinkontext.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/konzept.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/konzept/integration-isyfact.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/images/vorlage-systementwurf/ueberblick-teilsysteme.png
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/konfiguration.adoc
  isyfact-standards-doc/src/docs/antora/modules/release/pages/migrationsleitfaden.adoc
  isyfact-standards-doc/src/docs/antora/modules/release/pages/releasenotes.adoc
Labels: Review effort [1-5]: 2, Documentation

#515 fix: IFS-3956: deleted unused ORT config files
  .github/workflows/maven_dependency_scan.yml
  .github/workflows/oss_review_toolkit.yml
  evaluator.rules.kts
  isyfact-standards-doc/src/docs/antora/antora.yml
  license-classifications.yml
  ort-reports/AsciiDoc_cve_summary_report_template.html
Labels: configuration changes, Review effort [1-5]: 1, Bug fix

#528 chore: IFS-4031 updated enforced maven version to 3.6.3
  pom.xml
Labels: enhancement, Review effort [1-5]: 1

#509 Docs build template for triggering documentation build
  .github/workflows/docs_build.yml
Labels: configuration changes, Review effort [1-5]: 2, enhancement

#532 feat: IFS-0000: increase dependabot PR limit to 10
  .github/dependabot.yml
Labels: enhancement, Review effort [1-5]: 1

#540 IFS-3956: Added Antora token
  .github/workflows/maven_dependency_scan.yml
Labels: Review effort [1-5]: 2, enhancement
