Repository IsyFact/isyfact-standards, pull requests merged in 2024-01, with the labels that each got.

#192 ci: upload reports on test/code quality failures
  .github/workflows/maven_build_template.yml
Labels: ci, medium

#195 ci: add reusable job to compute version for build
  .github/workflows/next_version.yml
Labels: ci, medium

#198 ci: ISY-656 add next version job to build workflow (master)
  .github/workflows/maven_build.yml
Labels: ci, medium

#197 ci: add next version job to build workflow (release/3.x)
  .github/workflows/maven_build.yml
Labels: ci, medium

#191 ci: DependaBot Version Updates on release/3.x-Branch
  .github/dependabot.yml
Labels: ci, medium

#162 refactor: ISY-536: solve sonarcloud security issue
  isy-ueberwachung/src/main/java/de/bund/bva/isyfact/ueberwachung/common/konstanten/EreignisSchluessel.java
  isy-ueberwachung/src/main/java/de/bund/bva/isyfact/ueberwachung/service/loadbalancer/LoadbalancerServlet.java
  isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/service/loadbalancer/TestLoadbalancerServlet.java
Labels: high

#230 docs: ISY-763 Edited current documentation
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/konzept/integration-isyfact.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben/inhalt.adoc
Labels: docs

#236 docs: hotfix: Fixed asciidoc warnings
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
Labels: fix, ready for review, high

#239 docs: hotfix: Removed duplicate code and fixed asciidoc warnings
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
Labels: fix, ready for review, medium

#241 ISY-615: adjust templates for snapshots
  .github/workflows/maven_build_template.yml
  .github/workflows/maven_deploy_template.yml
Labels: ci

#163 ci: ISY-615 adjust workflows to deploy snapshots
  .github/workflows/maven_build.yml
  .github/workflows/maven_release.yml
Labels: ci, high

#243 ISY-615: fix repository layout for snapshot deployment
  .github/workflows/maven_build.yml
Labels: ci

#178 ci: ISY-615 adjust workflows to deploy snapshots (release/2.x)
  .github/workflows/maven_build.yml
  .github/workflows/maven_release.yml
Labels: ci, medium

#244 ISY-615: fix check for snapshot version
  .github/workflows/maven_deploy_template.yml
Labels: ci

#161 [Sprint 90] ISY-546 (2.x): Abraeumen des SecurityContexts im NutzerAuthentifizierungInterceptor
  CHANGELOG.md
  isy-sicherheit/CHANGELOG.md
  isy-sicherheit/src/main/java/de/bund/bva/isyfact/sicherheit/annotation/NutzerAuthentifizierungInterceptor.java
Labels: high

#200 [Sprint 93] ISY-650 (IF 2.x): Auslesen X-Correlation-ID Header
  CHANGELOG.md
  isy-aufrufkontext/CHANGELOG.md
  isy-aufrufkontext/src/main/java/de/bund/bva/isyfact/aufrufkontext/autoconfigure/MdcFilterAutoConfiguration.java
  isy-aufrufkontext/src/test/java/de/bund/bva/isyfact/aufrufkontext/autoconfigure/MdcFilterAutoConfigurationOverrideFilterRegistrationBeanTest.java
Labels: medium

#201 [Sprint 93] ISY-651: Nutzungsvorgaben Rest - Setzen X-Correlation-ID Header
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-service-rest/pages/nutzungsvorgaben/inhalt.adoc
Labels: medium

#202 [Sprint 93] ISY-651 (IF 2.x): Nutzungsvorgaben Rest - Setzen X-Correlation-ID Header
  CHANGELOG.md
  isy-service-rest/src/docs/asciidoc/konzept/inhalt.adoc
Labels: medium

#207 [Sprint 93] ISY-651 (IF 3.x): Nutzungsvorgaben Rest - Setzen X-Correlation-ID Header
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-service-rest/pages/nutzungsvorgaben/inhalt.adoc
Labels: medium

#246 Feature/isy 813 commit message checker
  .github/workflows/commit_message_checker_template.yml
Labels: medium

#259 ci: 813-ISY initial commit
  .github/workflows/commit_message_checker.yml
Labels: medium

#258 Feature/2.x commit message checker
  .github/workflows/commit_message_checker.yml
Labels: medium

#249 ISY-797 build templates without extensions & remove docs about PDF generation (3.x)
  isyfact-standards-doc/assembly-systementwurf.xml
  isyfact-standards-doc/assembly-systemhandbuch.xml
  isyfact-standards-doc/pom.xml
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/releasenotes.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systementwurf.pdf
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systementwurf.zip
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systemhandbuch.pdf
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systemhandbuch.zip
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/java-programmierkonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/namenskonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorgaben-dokumentation.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorgaben-dokumentation/dokumentationstypen.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systementwurf/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systemhandbuch/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systemhandbuch/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlagen.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/anwendungsanforderung.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/architekturregel.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/bedienkonzept.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/caution.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/important.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/note.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/sicherheit.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/tip.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/warning.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/bearbeitung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/changelog-doku.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/einfuehrung.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/einleitung/einfuehrung.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/erstellung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/erstellung/erstellung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/erstellung/erstellung-asciidoctorj.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/generierung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/generierung/generierung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/generierung/generierung-asciidoctorj.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/kopiervorlage.adoc
Labels: medium

#250 ISY-797 build templates without extensions & remove docs about PDF generation (4.x)
  isyfact-standards-doc/assembly-systementwurf.xml
  isyfact-standards-doc/assembly-systemhandbuch.xml
  isyfact-standards-doc/pom.xml
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systementwurf.pdf
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systementwurf.zip
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systemhandbuch.pdf
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systemhandbuch.zip
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/java-programmierkonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/namenskonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorgaben-dokumentation.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorgaben-dokumentation/dokumentationstypen.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systementwurf/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systemhandbuch/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systemhandbuch/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlagen.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/anwendungsanforderung.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/architekturregel.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/bedienkonzept.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/caution.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/important.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/note.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/sicherheit.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/tip.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/images/handbuch/warning.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/bearbeitung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/bearbeitung/bearbeitung-asciidoctorj.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/changelog-doku.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/einfuehrung.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/einleitung/einfuehrung.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/erstellung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/erstellung/erstellung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/erstellung/erstellung-asciidoctorj.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/generierung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/generierung/generierung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/generierung/generierung-asciidoctorj.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/kopiervorlage.adoc
Labels: medium
