Repository IsyFact/isyfact-standards, pull requests merged in 2024-02, with the labels that each got.

#245 ISY-866: Dependabot Updates (release/3.x)
  isyfact-products-bom/CHANGELOG.md
  isyfact-products-bom/pom.xml
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Produktvorgaben_Bibliotheken_Anwendungsentwicklung_Java_Spring_Entwicklung.csv
  pom.xml
Labels: build, medium

#209 [Sprint 93] ISY-658 (IF 3.x): StelltLoggingKontextBereit setzt generierte Korrelations-ID nicht in AufrufKontextTo
  CHANGELOG.md
  isy-serviceapi-core/CHANGELOG.md
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/aop/StelltLoggingKontextBereitInterceptor.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/StelltLoggingKontextBereitAspectTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/StelltLoggingKontextBereitTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/service/httpinvoker/v1_0_0/DummyKontextServiceImpl.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/service/httpinvoker/v1_0_0/DummyKontextServiceRemoteBean.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/test/LoggingKontextAspectService.java
  isyfact-standards-doc/src/docs/antora/modules/isy-logging/pages/nutzungsvorgaben/inhalt.adoc
Labels: medium

#187 [Sprint 92] ISY-653 HttpInvoker setzt Authorization Header nicht wenn isy security verwendet wird
  CHANGELOG.md
  isy-serviceapi-core/CHANGELOG.md
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/common/konstanten/EreignisSchluessel.java
  isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/TimeoutWiederholungHttpInvokerRequestExecutor.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/IsyHttpInvokerServiceExporterIntegrationTest.java
  isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/TimeoutWiederholungHttpInvokerRequestExecutorTest.java
Labels: medium

#256 docs: ISY-779: Decribe IsyFact dependency import after IsyFact-BOM removal
  CHANGELOG.md
  isyfact-standards-bom/pom.xml
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/inhalt.adoc
Labels: medium

#267 ISY-844: Adjustments for new documentation build (release/3.x)
  .github/workflows/docs_build.yml
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systementwurf.pdf
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systementwurf.zip
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systemhandbuch.pdf
  isyfact-standards-doc/src/docs/antora/modules/methodik/attachments/vorlage-generated/IsyFact-Vorlage-Systemhandbuch.zip
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/einfuehrung.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/erstellung-antora.adoc
  isyfact-standards-doc/src/docs/antora/modules/werkzeuge/pages/dokumentation/generierung-antora.adoc
Labels: ci, docs

#226 ISY-737 java language level 17
  CHANGELOG.md
  isy-logging/pom.xml
  isy-persistence/pom.xml
  isy-sonderzeichen/pom.xml
  isy-task/pom.xml
  isy-ueberwachung/pom.xml
  isyfact-products-bom/pom.xml
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Produktvorgaben_Allgemein_Basistechnologie.csv
  pom.xml
Labels: medium

#281 Isy 876 update validation for toast messages documentation
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/bedienkonzept.adoc
Labels: docs, ready for review, medium
