Repository IsyFact/isyfact-standards, pull requests merged in 2024-09, with the labels that each got.

#555 docs: IFS-4064 rewrite reference architecture for backends
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/detailkonzept-anwendungskern/IFBestAWK.png
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/referenzarchitektur-it-system/architektur-it-system-awk.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/referenzarchitektur-it-system/architektur-it-system-batch.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/referenzarchitektur-it-system/architektur-it-system-datenzugriff.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/referenzarchitektur-it-system/architektur-it-system-service.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/referenzarchitektur-it-system/architektur-it-system.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-anwendungskern/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-anwendungskern/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-datenzugriff/einordnung-ziele.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/referenzarchitektur-it-system/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/referenzarchitektur-it-system/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/vorstellung/isyfact-standards.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/pages/nutzungsvorgaben/umsetzung-datenzugriff.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/namenskonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/anwendungskern.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/architektur-backend.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/persistenz.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/querschnitt.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/service.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/batch/architektur-batch-system.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/index.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/konfiguration.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/it-system.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/technisch-infrastrukturell.adoc
  isyfact-standards-doc/src/docs/antora/modules/release/pages/releasenotes.adoc
Labels: Documentation, Review effort [1-5]: 3

#577 [Sprint 113] IFS-4229 use correct version property for mapstruct
  isyfact-products-bom/pom.xml
Labels: Review effort [1-5]: 1, bug_fix

#507 feat: IFS-3611 Create pr_agent.yml
  .github/workflows/pr_agent.yml
Labels: configuration changes, Review effort [1-5]: 2

#553 IFS-2853: CVE Scan for Dependencies in Dependency Management
  .github/workflows/maven_dependency_scan.yml
  isyfact-products-bom/pom.xml
  pom.xml
Labels: configuration changes, Review effort [1-5]: 2, enhancement

#576 docs: IFS-4007 it-system table removed
  isyfact-standards-doc/src/docs/antora/modules/isy-service-rest/pages/konzept/docinfo.adoc
Labels: Documentation, Review effort [1-5]: 1
