Repository IsyFact/isyfact-standards, pull requests merged in 2024-10, with the labels that each got.

#572 chore: IFS-4212 replace @ManualTask with @OnceTask
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben.adoc
Labels: Documentation, Review effort [1-5]: 1

#583 docs: IFS-4084 fix usage of term "IT-System" in module "einstieg"
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/vorstellung/isyfact-standards.adoc
Labels: Review effort [1-5]: 2, enhancement, Documentation

#587 chore: IFS-4064 fix changelog entry
  CHANGELOG.md
Labels: Documentation, Review effort [1-5]: 1

#585 [Sprint-114] IFS-4006 Release IFS-3.2.0 for IF 3.2.0
  CHANGELOG.md
  isy-task/CHANGELOG.md
  isyfact-standards-bom/pom.xml
  isyfact-standards-doc/src/docs/antora/antora.yml
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/nutzungsvorgaben/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-util/pages/nutzungsvorgaben/changelog.adoc
Labels: Review effort [1-5]: 2, enhancement, Documentation

#590 [Sprint 114] IFS-4006 Release IFS-3.2.0 set 3.3.0 SNAPSHOT
  .gitlab-ci.yml
  CHANGELOG.md
  isyfact-standards-doc/pom.xml
  isyfact-standards-doc/src/docs/antora/antora.yml
Labels: configuration changes, Review effort [1-5]: 2, enhancement, Documentation

#586 docs: IFS-4190 rewrite reference architecture for "Anwendungskern"
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/detailkonzept-anwendungskern/DependencyInjection.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/detailkonzept-anwendungskern/SpringBeansBeispiel.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-anwendungskern/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-anwendungskern/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-anwendungskern/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-anwendungskern/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-datenzugriff/einordnung-ziele.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/namenskonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/anwendungskern.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/architektur-backend.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/aufbau_fachkomponente_awk.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/persistenz.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/querschnitt.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/service.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/teilsysteme-aufbau.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/anwendungskern.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/spring.adoc
  isyfact-standards-doc/src/docs/antora/modules/release/pages/migrationsleitfaden.adoc
  isyfact-standards-doc/src/docs/antora/modules/release/pages/releasenotes.adoc
Labels: Documentation, Review effort [1-5]: 3

#603 Fix syntax error
  .github/workflows/maven_dependency_scan.yml
Labels: Review effort [1-5]: 1

#601 docs: IFS-4225 Abschnitt Nutzungsarten einer Anwendung geloescht
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/CallFAmGuX.png
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch.adoc
Labels: Review effort [1-5]: 1
