Repository IsyFact/isyfact-standards, pull requests merged in 2024-11, with the labels that each got.

#602 docs: IFS-4192 rewrite page about service layer
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/detailkonzept-service/archversServ.png
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-datenzugriff/einordnung-ziele.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-service/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/konzept/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/java-programmierkonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/teilsysteme-aufbau.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/extintServ.png
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/services/kommunikation-externe-systeme.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/services/versionierung.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/anwendungskern.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/serviceschicht.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/spring.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/services.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/technisch-infrastrukturell/availability.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/technisch-infrastrukturell/betriebliche-aspekte.adoc
  isyfact-standards-doc/src/docs/antora/modules/release/pages/releasenotes.adoc
Labels: Review effort [1-5]: 3

#607 docs: IFS-4193 rewrite page about persistence layer
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/bausteine/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/bausteine/pages/bausteine.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-datenzugriff/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-datenzugriff/einordnung-ziele.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-datenzugriff/historisierung.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-datenzugriff/persistenzlogik.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-datenzugriff/versionierung.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/images/aufbau_fachkomponente_persistenzschicht_spring_data.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/pages/konzept.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/pages/konzept/historisierung.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/pages/konzept/vorgaben-konventionen.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/pages/nutzungsvorgaben/historisierung.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/pages/nutzungsvorgaben/konfiguration.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/pages/nutzungsvorgaben/umsetzung-persistenzschicht.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/namenskonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorgaben-dokumentation/dokumentationstypen.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systementwurf/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systemhandbuch/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/backend/aufbau_fachkomponente_persistenz.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/index.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/konfiguration.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/persistenzschicht.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/spring.adoc
  isyfact-standards-doc/src/docs/antora/modules/release/pages/releasenotes.adoc
Labels: Review effort [1-5]: 3

#612 fix: ifs-0000: commented ORT since it's not working currently
  .github/workflows/maven_dependency_scan.yml
Labels: Review effort [1-5]: 1

#608 Feature/ifs 3029 update spring config guidelines
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/spring.adoc
Labels: Review effort [1-5]: 2

#614 docs: IFS-4209 correct references for removed glossary entrys
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/isy-exception-core/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-logging/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-persistence/pages/nutzungsvorgaben/umsetzung-persistenzschicht.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-polling/pages/nutzungsvorgaben/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/konzept.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-util/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-util/pages/nutzungsvorgaben/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/anleitung-datenflussdiagramme/01-einleitung.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/anleitung-datenflussdiagramme/03-datenfluesse-xyz.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/anleitung-datenflussdiagramme/04-datenfluesse-abc.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorgaben-dokumentation/dokumentationstypen.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systemspezifikation/03-geschaeftsprozesse.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systemspezifikation/13-anhang.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/fachlich.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/index.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/backend/anwendungskern.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/services.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/technisch-infrastrukturell/betriebliche-aspekte.adoc
Labels: Review effort [1-5]: 2

#624 IFS-4385: Updating Spring Security to 5.8.15, updating workflow templates
  .github/workflows/commit_message_checker.yml
  .github/workflows/dependabot_merge.yml
  .github/workflows/dependency_review.yml
  .github/workflows/docs_build.yml
  .github/workflows/maven_build.yml
  .github/workflows/maven_dependency_scan.yml
  .github/workflows/maven_release.yml
  .github/workflows/pr_agent.yml
  CHANGELOG.md
  isyfact-products-bom/CHANGELOG.md
  isyfact-products-bom/pom.xml
  isyfact-standards-doc/src/docs/antora/modules/changelog/pages/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/produktkatalog/changelog.adoc
Labels: Review effort [1-5]: 2

#628 IFS-4385: Setting branch reference for Quality Gate check to 3.2.1
  .github/workflows/maven_release.yml
Labels: Review effort [1-5]: 1

#622 fix: IFS-4203 Correct link checker findings
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Negativliste_Bibliotheken_Anwendungsentwicklung.csv
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Negativliste_Standards.csv
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Produktvorgaben_Allgemein_Systemsoftware.csv
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Produktvorgaben_Bibliotheken_Anwendungsentwicklung_Java_Spring_Entwicklung.csv
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/konzept/integration-isyfact.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/konzept/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-schnittstellendokumentation/01-allgemeines.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systemspezifikation/07-druckausgaben.adoc
Labels: Review effort [1-5]: 2

#632 docs: IFS-4194 rewrite pages about batches
  CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/images/detailkonzept-batch/architektur-it-system-batch-parts.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/changelog.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/docinfo.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/master.adoc
  isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/thisdoc.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/vorstellung/isyfact-standards.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/java-programmierkonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/namenskonventionen/inhalt.adoc
  isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorgaben-dokumentation/dokumentationstypen.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/batch/BeanGriffBat.png
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/batch/GrobArchBatCanv.png
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/batch/SchemTabBatStat.dn.png
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/batch/architektur-batch-parts.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/batch/architektur-batch-system.dn.svg
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/images/software-technisch/batch/batch-job.png
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/nav.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/fachlich.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/index.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/batch.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/batch/ausnahmeregelungen.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/batch/batchrahmen.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/batch/batchsteuerung.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/frontend.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/it-system.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/software-technisch/services.adoc
  isyfact-standards-doc/src/docs/antora/modules/referenzarchitektur/pages/tailoring.adoc
  isyfact-standards-doc/src/docs/antora/modules/release/pages/releasenotes.adoc
Labels: Review effort [1-5]: 5

#631 Feature/ifs 3916/ref impl doku antora integration
  isyfact-standards-doc/src/docs/antora/modules/einstieg/nav.adoc
Labels: Review effort [1-5]: 1

#639 [Sprint 116] IFS-4316 update product catalog 3.x
  CHANGELOG.md
  isyfact-products-bom/CHANGELOG.md
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Produktvorgaben_Bibliotheken_Anwendungsentwicklung_Java_Spring_Entwicklung.csv
Labels: Review effort [1-5]: 1

#638 [Sprint 116] IFS-4316 update product catalog 4.x
  CHANGELOG.md
  isyfact-products-bom/CHANGELOG.md
  isyfact-products-bom/pom.xml
  isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/produktkatalog/technologiestackJavaSpring.adoc
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Produktvorgaben_Allgemein_Bibliotheken_Anwendungsentwicklung_Sonstiges.csv
  isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Produktvorgaben_Bibliotheken_Anwendungsentwicklung_Java_Spring_Entwicklung.csv
Labels: Review effort [1-5]: 2

#626 [Sprint 116] IFS-4329 timertask im batch if3
  isy-task/CHANGELOG.md
  isy-task/src/main/java/de/bund/bva/isyfact/task/autoconfigure/IsyTaskAutoConfiguration.java
  isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben.adoc
Labels: Review effort [1-5]: 2
